#batch_size: 256
batch_size: 8
epochs: 20
eval_every_n_epochs: 1
fine_tune_from: 'Feb25_10-50-10_research10.saas.hku.hk'
log_every_n_steps: 25
weight_decay: 10e-6
fp16_precision: False
n_gpu: 2
gpu_ids: (0,1)

model:
#  out_dim: 512
#  base_model: "resnet18"
  out_dim: 1024
  base_model: "kimianet"

dataset:
  s: 1
#  input_shape: (224,224,3)
  input_shape: (1000,1000,3)
  num_workers: 10
  valid_size: 0.1

loss:
  temperature: 0.5
  use_cosine_similarity: True
